networkrail:
  target: dbt_big_bigquery

  outputs:
    dbt_big_bigquery:
      type: bigquery
      method: service-account
      project: essential-graph-395008
      dataset: dbt_big
      threads: 1
      keyfile: /workspaces/Portfolio/PROJECTS/EndToEndProjects/dbt/networkrail/AnalyticsDBTKeyfile.json
      location: asia-southeast1

    prod:
      type: bigquery
      method: service-account
      project: essential-graph-395008
      dataset: networkrail
      threads: 1
      keyfile: /workspaces/Portfolio/PROJECTS/EndToEndProjects/dbt/networkrail/AnalyticsDBTKeyfile.json
      location: asia-southeast1